//
//  ChapterControlView.swift
//  MedoDelirioBrasilia
//
//  Created by Rafael Claycon Schmitt on 30/07/26.
//

import SwiftUI

/// Compact chapter control for the now-playing screen: previous / current / next,
/// with the time left in the current chapter shown on the forward button.
///
/// Reads only the coarse `currentChapter` / `currentChapterIndex` from the
/// provider, so it re-evaluates a handful of times per episode. The per-tick
/// work (the countdown and its ring) lives in `ChapterAdvanceButton` — keeping it
/// out of here matters because the title marquee would restart its scroll if this
/// body ran twice a second.
struct ChapterControlView: View {

    let player: EpisodePlayer
    let chapterProvider: ChapterProvider
    let onTapTitle: () -> Void

    /// Visible circle. Smaller than the tap target on purpose — see `tapTarget`.
    static let buttonSize: CGFloat = 34

    /// Hit area, held at the 44pt minimum so shrinking the circle doesn't make
    /// the buttons harder to hit.
    static let tapTarget: CGFloat = 44

    var body: some View {
        if case .loaded(let chapters) = chapterProvider.state,
           let index = chapterProvider.currentChapterIndex,
           let chapter = chapterProvider.currentChapter {
            control(chapters: chapters, index: index, chapter: chapter)
        }
    }

    private func control(chapters: [EpisodeChapter], index: Int, chapter: EpisodeChapter) -> some View {
        // Buttons keep their intrinsic width so the title gets everything left
        // over — giving all three columns `maxWidth: .infinity` would split the
        // row in thirds and starve the title.
        HStack(spacing: .spacing(.small)) {
            previousButton

            Button(action: onTapTitle) {
                VStack(spacing: .spacing(.xSmall)) {
                    Text(chapter.title)
                        .font(.headline)
                        .foregroundStyle(.primary)
                        .marquee(spacing: 40, delay: 2, speedBasis: .velocity(40), fadeWidth: 16, centersWhenFitting: true)

                    // The two small lines are grouped tightly so the second one
                    // costs the row a few points of height rather than a full
                    // stack gap.
                    VStack(spacing: .spacing(.xxxSmall)) {
                        Text("\(index + 1) de \(chapters.count)")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .monospacedDigit()

                        if Self.showsAutoGeneratedLabel {
                            HStack(spacing: .spacing(.xxxSmall)) {
                                Text("Capítulos Auto-Gerados")
                                    .font(.caption2)
                                    .fontWeight(.bold)
                                    .foregroundStyle(.secondary)

                                Self.betaTag
                            }
                        }
                    }
                }
                .frame(maxWidth: .infinity)
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
            .accessibilityLabel(
                "Capítulo \(index + 1) de \(chapters.count): \(chapter.title)."
                + (Self.showsAutoGeneratedLabel ? " Capítulos auto-gerados, beta." : "")
                + " Toque para ver todos."
            )

            ChapterAdvanceButton(
                player: player,
                chapterStart: chapter.start,
                chapterEnd: chapterProvider.end(ofChapterAt: index, episodeDuration: player.duration),
                size: Self.buttonSize,
                isEnabled: index < chapters.count - 1,
                action: advance
            )
        }
        // Claws back part of the enclosing screen padding so the title has more
        // room to breathe than the controls stacked below it.
        .padding(.horizontal, -.spacing(.small))
    }

    /// Hidden for now. Flip to `true` to bring back the "Capítulos Auto-Gerados"
    /// line and its BETA tag under the chapter counter.
    private static let showsAutoGeneratedLabel = false

    // MARK: - Beta Tag

    /// Fixed 9pt rather than a Dynamic Type style: this sits inside an already
    /// three-line column, and a tag that scales would push the control taller than
    /// the buttons beside it.
    private static var betaTag: some View {
        Text("BETA")
            .font(.system(size: 9, weight: .heavy))
            .foregroundStyle(Color.darkerGreen)
            .padding(.horizontal, .spacing(.xxxSmall))
            .padding(.vertical, 1)
            .background(
                Capsule()
                    .fill(Color.darkerGreen.opacity(0.18))
            )
            .accessibilityHidden(true)
    }

    // MARK: - Previous

    private var previousButton: some View {
        // Matches `ChapterAdvanceButton`'s button-plus-caption structure so
        // both columns are the same height and their circles land on the
        // same line under the HStack's center alignment — otherwise the
        // forward button's remaining-time caption pushes its circle above
        // center, leaving this one looking low by comparison.
        VStack(spacing: .spacing(.xxxSmall)) {
            Button(action: goBack) {
                Image(systemName: "chevron.left")
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(.primary)
                    .frame(width: Self.buttonSize, height: Self.buttonSize)
                    .background(Circle().fill(.quaternary))
                    .frame(width: Self.tapTarget, height: Self.tapTarget)
                    .contentShape(Circle())
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Capítulo anterior")

            Text(" ")
                .font(.caption)
                .hidden()
                .accessibilityHidden(true)
        }
    }

    // MARK: - Actions

    private func goBack() {
        guard let target = chapterProvider.previousChapterStart(from: player.currentTime) else { return }
        seek(to: target)
    }

    private func advance() {
        guard let target = chapterProvider.nextChapterStart() else { return }
        seek(to: target)
    }

    private func seek(to time: TimeInterval) {
        UIImpactFeedbackGenerator(style: .light).impactOccurred()
        player.seek(to: time)
        // The provider is normally driven by the playback observer, which only
        // ticks while playing — nudge it so a seek made while paused updates the
        // control immediately.
        chapterProvider.update(currentTime: time)
    }
}

// MARK: - Advance Button

/// Forward button with a ring showing progress through the current chapter and
/// the time remaining beneath it.
///
/// Isolated from `ChapterControlView` because it reads `player.currentTime`, so
/// only this subtree re-renders on each playback tick.
private struct ChapterAdvanceButton: View {

    let player: EpisodePlayer
    let chapterStart: TimeInterval
    let chapterEnd: TimeInterval?
    let size: CGFloat
    let isEnabled: Bool
    let action: () -> Void

    var body: some View {
        let remaining = remainingTime

        VStack(spacing: .spacing(.xxxSmall)) {
            Button(action: action) {
                ZStack {
                    Circle()
                        .fill(.quaternary)

                    Circle()
                        .trim(from: 0, to: progress)
                        .stroke(Color(.systemGray2), style: StrokeStyle(lineWidth: 2, lineCap: .round))
                        .rotationEffect(.degrees(-90))
                        .padding(1)

                    Image(systemName: "chevron.right")
                        .font(.footnote.weight(.semibold))
                        .foregroundStyle(.primary)
                }
                .frame(width: size, height: size)
                .frame(width: ChapterControlView.tapTarget, height: ChapterControlView.tapTarget)
                .contentShape(Circle())
            }
            .buttonStyle(.plain)
            .disabled(!isEnabled)
            .opacity(isEnabled ? 1 : 0.4)

            Text(remaining.map(Self.formattedRemaining) ?? " ")
                .font(.caption)
                .foregroundStyle(.secondary)
                .monospacedDigit()
        }
        .accessibilityElement(children: .ignore)
        .accessibilityLabel(accessibilityLabel(remaining: remaining))
        .accessibilityAddTraits(.isButton)
    }

    /// How far through the current chapter playback has moved, 0...1.
    private var progress: CGFloat {
        guard let chapterEnd, chapterEnd > chapterStart else { return 0 }
        let elapsed = player.currentTime - chapterStart
        return min(max(CGFloat(elapsed / (chapterEnd - chapterStart)), 0), 1)
    }

    private var remainingTime: TimeInterval? {
        guard let chapterEnd else { return nil }
        return max(chapterEnd - player.currentTime, 0)
    }

    private func accessibilityLabel(remaining: TimeInterval?) -> String {
        guard isEnabled else { return "Último capítulo" }
        guard let remaining else { return "Próximo capítulo" }
        let minutes = Int(remaining) / 60
        let seconds = Int(remaining) % 60
        return "Próximo capítulo, faltam \(minutes) minutos e \(seconds) segundos"
    }

    /// Unit-suffixed countdown — `4min` above a minute, ticking down by the second
    /// as `32s` only in the final minute, where the precision is worth something.
    /// Deliberately not the scrubber's `m:ss`: this label sits away from the
    /// scrubber, where a bare `4:32` reads as a position rather than a duration.
    private static func formattedRemaining(_ remaining: TimeInterval) -> String {
        let total = Int(remaining)
        let minutes = total / 60
        let seconds = total % 60

        if minutes < 1 { return "\(seconds)s" }
        if minutes < 60 { return "\(minutes)min" }
        return "\(minutes / 60)h \(minutes % 60)min"
    }
}

// MARK: - Preview

#Preview {
    struct Host: View {
        let player: EpisodePlayer = {
            let player = EpisodePlayer()
            player.currentEpisode = .mockRecent
            player.duration = 3945
            player.currentTime = 620
            return player
        }()

        var body: some View {
            VStack(spacing: .spacing(.large)) {
                Text("II - 2026.18 - A peleja entre Jair e seu destino")
                    .font(.title2)
                    .fontDesign(.serif)
                    .fontWeight(.semibold)

                Text("20 de março de 2026")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)

                ChapterControlView(
                    player: player,
                    chapterProvider: .mockLoaded(),
                    onTapTitle: {}
                )
            }
            .padding(.horizontal, .spacing(.xLarge))
        }
    }
    return Host()
}
